title: Shayan Bastani's Portfolio
email: sh.cnct@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An Anthusiastic Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  Shayan-B

# Build settings
theme: jekyll-theme-minimal
show_downloads: false