title: Shayan Bastani's Portfolio
email: sh.cnct@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I have experience in various business domains and hold a 
  Bachelor's degree in Electronics Engineering. This educational 
  background provides me with a strong foundation in the mathematics 
  underpinning data science and machine learning algorithms. 

  My diverse business experience enables me to incorporate 
  insights into the data analysis process, ensuring the derivation 
  of optimal outcomes for businesses.


github_username:  Shayan-B
linkedin_username: shayan-bastani

# Build settings
theme: jekyll-theme-minimal
show_downloads: false
logo: /assets/img/shayan.png