title: Shayan Bastani's Portfolio
email: sh.cnct@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An Enthusiastic Data Scientist

github_username:  Shayan-B
linkedin_username: shayan-bastani

# Build settings
theme: jekyll-theme-minimal
show_downloads: false
logo: /assets/img/shayan.png